In [1]:
import pandas as pd
import numpy as np

In [6]:
all_nba = pd.read_csv("../nba_data/all_nba_by_year.csv")
all_nba.head()

,Season,Lg,Tm,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,2018-19,NBA,1st,Nikola Jokić C,Giannis Antetokounmpo F,Paul George F,James Harden G,Stephen Curry G
1,2018-19,NBA,2nd,Joel Embiid C,Kevin Durant F,Kawhi Leonard F,Damian Lillard G,Kyrie Irving G
2,2018-19,NBA,3rd,Rudy Gobert C,LeBron James F,Blake Griffin F,Kemba Walker G,Russell Westbrook G
3,2017-18,NBA,1st,Anthony Davis C,LeBron James F,Kevin Durant F,Damian Lillard G,James Harden G
4,2017-18,NBA,2nd,Joel Embiid C,Giannis Antetokounmpo F,LaMarcus Aldridge F,Russell Westbrook G,DeMar DeRozan G

In [3]:
pd.DataFrame(np.array(next(all_nba.iterrows())[1][3:]).reshape(-1,1))

                         0
0           Nikola Jokić C
1  Giannis Antetokounmpo F
2            Paul George F
3           James Harden G
4          Stephen Curry G

In [18]:
def fix_season(season):
    return int(season[:4]) +1

In [19]:
df = pd.DataFrame()
for row in all_nba.iterrows():
    temp_data = row[1]
    if temp_data["Lg"] != "NBA":
        continue
    temp_df = pd.DataFrame(np.array(row[1][3:]).reshape(-1,1))
    temp_df["Season"] = fix_season(temp_data["Season"])
    temp_df["Team"] = temp_data["Tm"]
    df = df.append(temp_df, ignore_index=True)
df

                           0  Season Team
0             Nikola Jokić C    2019  1st
1    Giannis Antetokounmpo F    2019  1st
2              Paul George F    2019  1st
3             James Harden G    2019  1st
4            Stephen Curry G    2019  1st
..                       ...     ...  ...
850              Ralph Beard    1950  2nd
851            Frankie Brian    1950  2nd
852                 Al Cervi    1950  2nd
853              Fred Schaus    1950  2nd
854            Dolph Schayes    1950  2nd

[855 rows x 3 columns]

In [21]:
df.to_csv("../nba_data/all_nba_by_year.csv")