In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns; sns.set()
import os

In [2]:
os.getcwd()

'/Users/jdarius/Documents/Basketball_HOF'

In [1]:
files = os.listdir("nba_data")
path = "nba_data/"
data = {}
for file in files[:]:
    data[file] = pd.read_csv(path+file, encoding='latin')

NameError: name 'os' is not defined

In [4]:
data.keys()

dict_keys(['player_season_advanced.csv', '.DS_Store', 'mvp_by_year.csv', 'all_nba_by_year.csv', 'mvp_counts.csv', 'players_by_year.csv', 'bball_ref_hof_pred.csv', 'nba_champions.csv', 'dpoy_by_year.csv', 'player_playoff_totals.csv', 'finals_mvp_by_year.csv', 'player_season_totals.csv', 'all_star_game_counts.csv', 'all_league_counts.csv', 'all_star_by_year.csv'])

In [5]:
bball_ref = pd.read_csv("bball_ref_hof_pred.csv", encoding='latin').set_index("id")

In [6]:
train = bball_ref[bball_ref["LastYear"] <= 2005 ]

In [7]:
data["mvp_counts.csv"].set_index("id", inplace=True)

In [8]:
data["mvp_counts.csv"]

                            Name League  Count
id
abdulka01    Kareem Abdul-Jabbar    NBA      6
jordami01         Michael Jordan    NBA      5
russebi01           Bill Russell    NBA      5
chambwi01       Wilt Chamberlain    NBA      4
jamesle01           LeBron James    NBA      4
birdla01              Larry Bird    NBA      3
ervinju01          Julius Erving    ABA      3
johnsma02          Magic Johnson    NBA      3
malonmo01           Moses Malone    NBA      3
curryst01          Stephen Curry    NBA      2
danieme01            Mel Daniels    ABA      2
duncati01             Tim Duncan    NBA      2
malonka01            Karl Malone    NBA      2
nashst01              Steve Nash    NBA      2
pettibo01             Bob Pettit    NBA      2
antetgi01  Giannis Antetokounmpo    NBA      1
barklch01        Charles Barkley    NBA      1
bryanko01            Kobe Bryant    NBA      1
cousybo01              Bob Cousy    NBA      1
cowenda01            Dave Cowens    NBA      1
cunnibi01       Billy Cunningham    ABA      1
duranke01           Kevin Durant    NBA      1
ervinju01          Julius Erving    NBA      1
garneke01          Kevin Garnett    NBA      1
gilmoar01          Artis Gilmore    ABA      1
hardeja01           James Harden    NBA      1
hawkico01         Connie Hawkins    ABA      1
haywosp01        Spencer Haywood    ABA      1
iversal01          Allen Iverson    NBA      1
mcadobo01             Bob McAdoo    NBA      1
mcginge01        George McGinnis    ABA      1
nowitdi01          Dirk Nowitzki    NBA      1
onealsh01       Shaquille O'Neal    NBA      1
olajuha01        Hakeem Olajuwon    NBA      1
reedwi01             Willis Reed    NBA      1
roberos01        Oscar Robertson    NBA      1
robinda01         David Robinson    NBA      1
rosede01            Derrick Rose    NBA      1
unselwe01             Wes Unseld    NBA      1
waltobi01            Bill Walton    NBA      1
westbru01      Russell Westbrook    NBA      1

In [9]:
bball_ref = bball_ref.join(data["mvp_counts.csv"][["League", "Count"]].add_suffix("_mvp"),
                           on="id",how="left")
bball_ref["Count_mvp"].fillna("0", inplace=True)
bball_ref

,Name,Probability,LastYear,hof,League_mvp,Count_mvp
id,,,,,,
abdulka01,Kareem Abdul-Jabbar,1.0000,1989,1,NBA,6
jordami01,Michael Jordan,1.0000,2003,1,NBA,5
russebi01,Bill Russell,1.0000,1969,1,NBA,5
bryanko01,Kobe Bryant,1.0000,2016,1,NBA,1
jamesle01,LeBron James,1.0000,2020,0,NBA,4
...,...,...,...,...,...,...
wedmasc01,Scott Wedman,0.0150,1987,0,NaN,0
leeda02,David Lee,0.0147,2017,0,NaN,0
finlemi01,Michael Finley,0.0145,2010,0,NaN,0
brianfr01,Frankie Brian,0.0142,1956,0,NaN,0
smithph01,Phil Smith,0.0140,1983,0,NaN,0

In [10]:
dpoy = data["dpoy_by_year.csv"].copy()

In [11]:
dpoy_count = dpoy.groupby("id").agg("count").rename(columns={"Name":"Count_dpoy"})["Count_dpoy"]

In [12]:
bball_ref = bball_ref.join(dpoy_count, on="id", how="left")
bball_ref["Count_dpoy"].fillna("0", inplace=True)
bball_ref

,Name,Probability,LastYear,hof,League_mvp,Count_mvp,Count_dpoy
id,,,,,,,
abdulka01,Kareem Abdul-Jabbar,1.0000,1989,1,NBA,6,0
jordami01,Michael Jordan,1.0000,2003,1,NBA,5,1
russebi01,Bill Russell,1.0000,1969,1,NBA,5,0
bryanko01,Kobe Bryant,1.0000,2016,1,NBA,1,0
jamesle01,LeBron James,1.0000,2020,0,NBA,4,0
...,...,...,...,...,...,...,...
wedmasc01,Scott Wedman,0.0150,1987,0,NaN,0,0
leeda02,David Lee,0.0147,2017,0,NaN,0,0
finlemi01,Michael Finley,0.0145,2010,0,NaN,0,0
brianfr01,Frankie Brian,0.0142,1956,0,NaN,0,0
smithph01,Phil Smith,0.0140,1983,0,NaN,0,0

In [13]:
data["all_star_game_counts.csv"].rename(columns={"Games":"All_stars"},
                                       inplace=True)
data["all_star_game_counts.csv"].set_index("id", inplace=True)

In [14]:
bball_ref = bball_ref.join(data["all_star_game_counts.csv"][["All_stars"]],
                           on="id", how="left")
bball_ref["All_stars"].fillna("0", inplace=True)
bball_ref

,Name,Probability,LastYear,hof,League_mvp,Count_mvp,Count_dpoy,All_stars
id,,,,,,,,
abdulka01,Kareem Abdul-Jabbar,1.0000,1989,1,NBA,6,0,18
jordami01,Michael Jordan,1.0000,2003,1,NBA,5,1,13
russebi01,Bill Russell,1.0000,1969,1,NBA,5,0,12
bryanko01,Kobe Bryant,1.0000,2016,1,NBA,1,0,15
jamesle01,LeBron James,1.0000,2020,0,NBA,4,0,16
...,...,...,...,...,...,...,...,...
wedmasc01,Scott Wedman,0.0150,1987,0,NaN,0,0,1
leeda02,David Lee,0.0147,2017,0,NaN,0,0,2
finlemi01,Michael Finley,0.0145,2010,0,NaN,0,0,2
brianfr01,Frankie Brian,0.0142,1956,0,NaN,0,0,2
smithph01,Phil Smith,0.0140,1983,0,NaN,0,0,2

In [15]:
finals_mvp = data["finals_mvp_by_year.csv"].copy()
finals_mvp_count = finals_mvp.groupby("id").agg("count").rename(columns={"Name":"Count_finals_mvp"})["Count_finals_mvp"]
finals_mvp_count

id
abdulka01    2
barryri01    1
billuch01    1
birdla01     2
bryanko01    2
chambwi01    1
dumarjo01    1
duncati01    3
duranke01    2
havlijo01    1
iguodan01    1
jamesle01    3
johnsde01    1
johnsma02    3
jordami01    6
leonaka01    2
malonmo01    1
maxwece01    1
nowitdi01    1
olajuha01    2
onealsh01    3
parketo01    1
piercpa01    1
reedwi01     2
thomais01    1
unselwe01    1
wadedw01     1
waltobi01    1
westje01     1
whitejo01    1
worthja01    1
Name: Count_finals_mvp, dtype: int64

In [16]:
bball_ref = bball_ref.join(finals_mvp_count, on="id", how="left")
bball_ref["Count_finals_mvp"].fillna("0", inplace=True)
bball_ref

,Name,Probability,LastYear,hof,League_mvp,Count_mvp,Count_dpoy,All_stars,Count_finals_mvp
id,,,,,,,,,
abdulka01,Kareem Abdul-Jabbar,1.0000,1989,1,NBA,6,0,18,2
jordami01,Michael Jordan,1.0000,2003,1,NBA,5,1,13,6
russebi01,Bill Russell,1.0000,1969,1,NBA,5,0,12,0
bryanko01,Kobe Bryant,1.0000,2016,1,NBA,1,0,15,2
jamesle01,LeBron James,1.0000,2020,0,NBA,4,0,16,3
...,...,...,...,...,...,...,...,...,...
wedmasc01,Scott Wedman,0.0150,1987,0,NaN,0,0,1,0
leeda02,David Lee,0.0147,2017,0,NaN,0,0,2,0
finlemi01,Michael Finley,0.0145,2010,0,NaN,0,0,2,0
brianfr01,Frankie Brian,0.0142,1956,0,NaN,0,0,2,0
smithph01,Phil Smith,0.0140,1983,0,NaN,0,0,2,0

In [17]:
def get_team(team):
    try:
        if str(team) == "nan":
            return "None"
        else:
            team = team[5:]
            team = team.split("_")
            team[0] = team[0][0] + team[0][1:].lower()
            team_name = team[0]
            for word in team[1:]:
                word = word[0] + word[1:].lower()
                team_name = team_name + " " + word
            return team_name
    except:
        print(team)

In [18]:
team = "BOSTON_CELTICS".split("_")
print(team)
team[0] = "Boston"

['BOSTON', 'CELTICS']

In [19]:
get_team("Team.LOS_ANGELES_LAKERS")

'Los Angeles Lakers'

### Playoffs

In [20]:
playoff_totals = data["player_playoff_totals.csv"].copy()
playoff_totals["team"] = playoff_totals["team"].apply(get_team)
playoff_totals

,Unnamed: 0,age,assists,attempted_field_goals,attempted_free_throws,attempted_three_point_field_goals,blocks,defensive_rebounds,games_played,games_started,...,offensive_rebounds,personal_fouls,points,positions,slug,steals,team,total_rebounds,turnovers,year
0,0,31.0,6.0,22.0,4.0,0.0,0.0,0.0,3.0,0.0,...,0.0,6.0,9.0,"[<Position.GUARD: 'GUARD'>, <Position.FORWARD:...",armstcu01,0.0,None,0.0,0.0,1950.0
1,1,29.0,13.0,31.0,15.0,0.0,0.0,0.0,6.0,0.0,...,0.0,10.0,34.0,[<Position.SHOOTING_GUARD: 'SHOOTING GUARD'>],barkecl01,0.0,None,0.0,0.0,1950.0
2,2,25.0,4.0,25.0,6.0,0.0,0.0,0.0,2.0,0.0,...,0.0,10.0,22.0,[<Position.SMALL_FORWARD: 'SMALL FORWARD'>],barnhle01,0.0,None,0.0,0.0,1950.0
3,3,22.0,22.0,70.0,28.0,0.0,0.0,0.0,5.0,0.0,...,0.0,11.0,66.0,[<Position.GUARD: 'GUARD'>],beardra01,0.0,None,0.0,0.0,1950.0
4,4,28.0,17.0,61.0,29.0,0.0,0.0,0.0,8.0,0.0,...,0.0,38.0,57.0,"[<Position.FORWARD: 'FORWARD'>, <Position.CENT...",blackch01,0.0,None,0.0,0.0,1950.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9970,21.0,0.0,2.0,2.0,0.0,0.0,6.0,3.0,0.0,...,1.0,1.0,4.0,[<Position.CENTER: 'CENTER'>],williro04,0.0,Boston Celtics,7.0,0.0,2019.0
9971,9971,22.0,4.0,16.0,2.0,5.0,1.0,9.0,8.0,0.0,...,1.0,7.0,19.0,[<Position.POWER_FORWARD: 'POWER FORWARD'>],wilsodj01,0.0,Milwaukee Bucks,10.0,7.0,2019.0
9972,9972,23.0,1.0,4.0,7.0,1.0,1.0,1.0,4.0,0.0,...,1.0,3.0,8.0,[<Position.POWER_FORWARD: 'POWER FORWARD'>],yabusgu01,0.0,Boston Celtics,2.0,1.0,2019.0
9973,9973,30.0,15.0,42.0,7.0,8.0,3.0,19.0,4.0,4.0,...,9.0,10.0,42.0,[<Position.POWER_FORWARD: 'POWER FORWARD'>],youngth01,11.0,Indiana Pacers,28.0,5.0,2019.0
9974,9974,21.0,1.0,18.0,3.0,0.0,2.0,11.0,4.0,3.0,...,11.0,5.0,20.0,[<Position.CENTER: 'CENTER'>],zubaciv01,2.0,Los Angeles Clippers,22.0,4.0,2019.0

In [21]:
champs = data["nba_champions.csv"]
champs["team_year"] = champs["Year"].astype("str") + " " + champs["Champion"]

playoff_totals["team_year"] = playoff_totals["year"].astype("int64").astype("str") + " " + playoff_totals["team"]

In [22]:
playoff_totals["Championships"] = playoff_totals["team_year"].apply(lambda x: x in list(champs["team_year"]))
with pd.option_context("display.max_rows", 1000):
    display(playoff_totals[playoff_totals["slug"] == "abdulka01"])

,Unnamed: 0,age,assists,attempted_field_goals,attempted_free_throws,attempted_three_point_field_goals,blocks,defensive_rebounds,games_played,games_started,...,points,positions,slug,steals,team,total_rebounds,turnovers,year,team_year,Championships
1423,1423,22.0,41.0,245.0,101.0,0.0,0.0,0.0,10.0,0.0,...,352.0,[<Position.CENTER: 'CENTER'>],abdulka01,0.0,Milwaukee Bucks,168.0,0.0,1970.0,1970 Milwaukee Bucks,False
1511,1511,23.0,35.0,295.0,101.0,0.0,0.0,0.0,14.0,0.0,...,372.0,[<Position.CENTER: 'CENTER'>],abdulka01,0.0,Milwaukee Bucks,238.0,0.0,1971.0,1971 Milwaukee Bucks,True
1596,1596,24.0,56.0,318.0,54.0,0.0,0.0,0.0,11.0,0.0,...,316.0,[<Position.CENTER: 'CENTER'>],abdulka01,0.0,Milwaukee Bucks,200.0,0.0,1972.0,1972 Milwaukee Bucks,False
1684,1684,25.0,17.0,138.0,35.0,0.0,0.0,0.0,6.0,0.0,...,137.0,[<Position.CENTER: 'CENTER'>],abdulka01,0.0,Milwaukee Bucks,97.0,0.0,1973.0,1973 Milwaukee Bucks,False
1775,1775,26.0,78.0,402.0,91.0,0.0,39.0,186.0,16.0,0.0,...,515.0,[<Position.CENTER: 'CENTER'>],abdulka01,20.0,Milwaukee Bucks,253.0,0.0,1974.0,1974 Milwaukee Bucks,False
2093,2093,29.0,45.0,242.0,120.0,0.0,38.0,144.0,11.0,0.0,...,381.0,[<Position.CENTER: 'CENTER'>],abdulka01,19.0,Los Angeles Lakers,195.0,0.0,1977.0,1977 Los Angeles Lakers,False
2226,2226,30.0,11.0,73.0,9.0,0.0,12.0,27.0,3.0,0.0,...,81.0,[<Position.CENTER: 'CENTER'>],abdulka01,2.0,Los Angeles Lakers,41.0,14.0,1978.0,1978 Los Angeles Lakers,False
2354,2354,31.0,38.0,152.0,62.0,0.0,33.0,83.0,8.0,0.0,...,228.0,[<Position.CENTER: 'CENTER'>],abdulka01,8.0,Los Angeles Lakers,101.0,29.0,1979.0,1979 Los Angeles Lakers,False
2481,2481,32.0,46.0,346.0,105.0,0.0,58.0,130.0,15.0,0.0,...,479.0,[<Position.CENTER: 'CENTER'>],abdulka01,17.0,Los Angeles Lakers,181.0,55.0,1980.0,1980 Los Angeles Lakers,True
2610,2610,33.0,12.0,65.0,28.0,0.0,8.0,37.0,3.0,0.0,...,80.0,[<Position.CENTER: 'CENTER'>],abdulka01,3.0,Los Angeles Lakers,50.0,11.0,1981.0,1981 Los Angeles Lakers,False
2740,2740,34.0,51.0,221.0,87.0,0.0,45.0,86.0,14.0,0.0,...,285.0,[<Position.CENTER: 'CENTER'>],abdulka01,14.0,Los Angeles Lakers,119.0,41.0,1982.0,1982 Los Angeles Lakers,True
2878,2878,35.0,42.0,287.0,106.0,1.0,55.0,90.0,15.0,0.0,...,406.0,[<Position.CENTER: 'CENTER'>],abdulka01,17.0,Los Angeles Lakers,115.0,50.0,1983.0,1983 Los Angeles Lakers,False
3018,3018,36.0,79.0,371.0,120.0,0.0,45.0,117.0,21.0,0.0,...,502.0,[<Position.CENTER: 'CENTER'>],abdulka01,23.0,Los Angeles Lakers,173.0,45.0,1984.0,1984 Los Angeles Lakers,False
3201,3201,37.0,76.0,300.0,103.0,0.0,36.0,104.0,19.0,19.0,...,416.0,[<Position.CENTER: 'CENTER'>],abdulka01,23.0,Los Angeles Lakers,154.0,52.0,1985.0,1985 Los Angeles Lakers,True
3386,3386,38.0,49.0,282.0,61.0,0.0,24.0,57.0,14.0,14.0,...,362.0,[<Position.CENTER: 'CENTER'>],abdulka01,15.0,Los Angeles Lakers,83.0,42.0,1986.0,1986 Los Angeles Lakers,False
3570,3570,39.0,36.0,234.0,122.0,1.0,35.0,84.0,18.0,18.0,...,345.0,[<Position.CENTER: 'CENTER'>],abdulka01,8.0,Los Angeles Lakers,123.0,40.0,1987.0,1987 Los Angeles Lakers,True
3754,3754,40.0,36.0,304.0,71.0,2.0,37.0,82.0,24.0,24.0,...,338.0,[<Position.CENTER: 'CENTER'>],abdulka01,15.0,Los Angeles Lakers,131.0,46.0,1988.0,1988 Los Angeles Lakers,True
3942,3942,41.0,19.0,147.0,43.0,0.0,11.0,46.0,15.0,15.0,...,167.0,[<Position.CENTER: 'CENTER'>],abdulka01,5.0,Los Angeles Lakers,59.0,22.0,1989.0,1989 Los Angeles Lakers,False

In [23]:
playoff_totals = playoff_totals.groupby("slug").agg(np.sum)
playoff_totals.drop(["year", "age"], axis=1, inplace=True)
bball_ref = bball_ref.join(playoff_totals["Championships"], on="id", how="left")
playoff_totals.drop(["Championships"], axis=1, inplace=True)
playoff_totals = playoff_totals.add_suffix("_playoffs")

In [24]:
bball_ref = bball_ref.join(playoff_totals, on="id", how="left")

### Regular Season

In [25]:
season_totals = data["player_season_totals.csv"].copy()

In [26]:
def display_all(df):
    with pd.option_context("display.max_rows", 1000, 
                           "display.max_columns", 1000):
        display(df)

In [27]:
display_all(season_totals)

,Unnamed: 0,age,assists,attempted_field_goals,attempted_free_throws,attempted_three_point_field_goals,blocks,defensive_rebounds,games_played,games_started,made_field_goals,made_free_throws,made_three_point_field_goals,minutes_played,name,offensive_rebounds,personal_fouls,points,positions,slug,steals,team,total_rebounds,turnovers,year
0,0,31.0,176.0,516.0,241.0,0.0,0.0,0.0,63.0,0.0,144.0,170.0,0.0,0.0,Curly Armstrong,0.0,217.0,458.0,"[<Position.GUARD: 'GUARD'>, <Position.FORWARD:...",armstcu01,0.0,NaN,0.0,0.0,1950.0
1,1,29.0,109.0,274.0,106.0,0.0,0.0,0.0,49.0,0.0,102.0,75.0,0.0,0.0,Cliff Barker,0.0,99.0,279.0,[<Position.SHOOTING_GUARD: 'SHOOTING GUARD'>],barkecl01,0.0,NaN,0.0,0.0,1950.0
2,2,25.0,140.0,499.0,129.0,0.0,0.0,0.0,67.0,0.0,174.0,90.0,0.0,0.0,Leo Barnhorst,0.0,192.0,438.0,[<Position.SMALL_FORWARD: 'SMALL FORWARD'>],barnhle01,0.0,NaN,0.0,0.0,1950.0
3,3,24.0,20.0,82.0,31.0,0.0,0.0,0.0,13.0,0.0,21.0,17.0,0.0,0.0,Ed Bartels,0.0,27.0,59.0,[<Position.FORWARD: 'FORWARD'>],barteed01,0.0,NaN,0.0,0.0,1950.0
4,4,24.0,0.0,4.0,3.0,0.0,0.0,0.0,2.0,0.0,1.0,2.0,0.0,0.0,Ed Bartels,0.0,2.0,4.0,[<Position.FORWARD: 'FORWARD'>],barteed01,0.0,Team.NEW_YORK_KNICKS,0.0,0.0,1950.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23797,23797,29.0,1.0,2.0,0.0,1.0,0.0,4.0,2.0,0.0,0.0,0.0,0.0,11.0,Tyler Zeller,2.0,4.0,0.0,[<Position.CENTER: 'CENTER'>],zellety01,0.0,Team.ATLANTA_HAWKS,6.0,0.0,2019.0
23798,23798,29.0,3.0,28.0,18.0,0.0,3.0,9.0,4.0,1.0,16.0,14.0,0.0,82.0,Tyler Zeller,9.0,16.0,46.0,[<Position.CENTER: 'CENTER'>],zellety01,1.0,Team.MEMPHIS_GRIZZLIES,18.0,4.0,2019.0
23799,23799,22.0,53.0,331.0,132.0,0.0,22.0,212.0,59.0,25.0,183.0,93.0,0.0,1082.0,Ante Å½iÅ¾iÄ,108.0,113.0,459.0,[<Position.CENTER: 'CENTER'>],zizican01,13.0,Team.CLEVELAND_CAVALIERS,320.0,61.0,2019.0
23800,23800,21.0,25.0,193.0,66.0,0.0,27.0,108.0,33.0,12.0,112.0,57.0,0.0,516.0,Ivica Zubac,54.0,73.0,281.0,[<Position.CENTER: 'CENTER'>],zubaciv01,4.0,Team.LOS_ANGELES_LAKERS,162.0,33.0,2019.0
23801,23801,21.0,38.0,186.0,60.0,0.0,24.0,139.0,26.0,25.0,100.0,44.0,0.0,524.0,Ivica Zubac,61.0,64.0,244.0,[<Position.CENTER: 'CENTER'>],zubaciv01,10.0,Team.LOS_ANGELES_CLIPPERS,200.0,37.0,2019.0

In [28]:
season_totals.columns

Index(['Unnamed: 0', 'age', 'assists', 'attempted_field_goals',
       'attempted_free_throws', 'attempted_three_point_field_goals', 'blocks',
       'defensive_rebounds', 'games_played', 'games_started',
       'made_field_goals', 'made_free_throws', 'made_three_point_field_goals',
       'minutes_played', 'name', 'offensive_rebounds', 'personal_fouls',
       'points', 'positions', 'slug', 'steals', 'team', 'total_rebounds',
       'turnovers', 'year'],
      dtype='object')

In [29]:
season_totals.drop(["age", "team", "year"], axis=1, inplace=True)
season_totals = season_totals.groupby("slug").agg(np.sum)

In [30]:
bball_ref = bball_ref.join(season_totals, on="id", how="left")

### Advanced

In [31]:
np.max

In [32]:
advanced_stats = data["player_season_advanced.csv"].copy()
advanced_stats = advanced_stats[advanced_stats["year"] >= 1952]
advanced_stats = advanced_stats.drop(["year", "age", "name", "positions", "team"], axis=1)

In [33]:
ws = advanced_stats.groupby("slug").agg(np.max)["win_shares"]
vorp = advanced_stats.groupby("slug").agg(np.max)["value_over_replacement_player"]
ws

slug
abdelal01     2.1
abdulka01    25.4
abdulma01     5.4
abdulma02     6.8
abdulta01     2.0
             ...
zipsepa01     0.5
zizican01     2.0
zoetji01     -0.1
zopfbi01     -0.1
zubaciv01     1.8
Name: win_shares, Length: 4030, dtype: float64

In [34]:
ids = advanced_stats["slug"]
total_minutes = advanced_stats["minutes_played"] * advanced_stats["games_played"]
total_minutes.index = ids
advanced_stats.drop(["slug", "minutes_played", "games_played"], axis=1, inplace=True)

In [35]:
advanced_arr = np.array(advanced_stats) * np.array(total_minutes).reshape((-1, 1))

In [36]:
advanced_stats_mult = pd.DataFrame(advanced_arr, columns=advanced_stats.columns)
advanced_stats_mult.index = ids

In [37]:
total_minutes = total_minutes.groupby("slug").agg(np.sum)

In [38]:
advanced_stats_sum = advanced_stats_mult.groupby("slug").agg(np.sum)
advanced_stats_avg = np.array(advanced_stats_sum) / np.array(total_minutes).reshape((-1, 1))

/Users/jdarius/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide

In [39]:
advanced_stats_sum

,assist_percentage,block_percentage,box_plus_minus,defensive_box_plus_minus,defensive_rebound_percentage,defensive_win_shares,free_throw_attempt_rate,is_combined_totals,offensive_box_plus_minus,offensive_rebound_percentage,...,player_efficiency_rating,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares,win_shares_per_48_minutes
slug,,,,,,,,,,,,,,,,,,,,,
abdelal01,696038.7,242869.2,-619552.8,-158316.8,3498062.8,210378.7,46058.347,0.0,-468074.1,1821148.1,...,2414002.6,196705.0,252.828,2670329.9,97081.713,2650465.7,3841326.8,-55720.8,297911.5,15379.878
abdulka01,65677103.1,12869925.1,19502573.2,5487305.8,73708723.2,22485254.9,1486919.464,0.0,14010270.6,26135771.4,...,110741528.2,4136555.9,3314.447,66026539.3,2673026.668,32533299.1,58839375.8,19655641.6,65641327.7,1030995.384
abdulma01,36853449.4,13989.5,-53160.1,0.0,195853.0,2013321.8,451959.298,0.0,-53160.1,81139.1,...,22153563.2,55958.0,0.000,2148980.8,717247.755,0.0,0.0,0.0,5712364.2,113094.307
abdulma02,25172877.3,213534.8,-853754.9,-1648818.8,6942693.7,1494761.5,168761.404,0.0,757914.3,1718428.1,...,17192003.6,1733689.9,191834.491,4294102.0,570772.539,11590855.2,28357992.5,932004.8,4353629.0,88464.432
abdulta01,1702776.2,202706.5,-612326.5,-98362.8,2205162.3,183623.3,63692.993,0.0,-515741.2,1233028.0,...,2318806.3,402505.2,9687.200,1712508.4,94044.806,2721858.5,4190430.8,-41688.2,179586.6,7375.523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zipsepa01,582229.2,126831.6,-434630.4,-29666.4,1238642.4,56371.2,11474.724,0.0,-400514.4,141668.4,...,487314.0,86778.0,37530.336,674952.0,38457.996,1197115.2,1210464.0,-54142.8,-8151.6,-400.104
zizican01,517575.0,150518.0,-197433.6,-140223.0,1582879.2,20521.0,28436.546,0.0,-57210.6,764337.2,...,1199897.2,41726.8,0.000,1154456.8,42773.028,951057.6,1290594.0,-17781.8,134524.0,7135.794
zoetji01,798.0,1113.0,-1134.0,42.0,3717.0,0.0,0.000,0.0,-1176.0,2142.0,...,-168.0,315.0,0.000,2919.0,42.000,9324.0,2436.0,-21.0,-21.0,-25.830
zopfbi01,438755.2,0.0,0.0,0.0,0.0,8437.6,5632.098,0.0,0.0,0.0,...,202502.4,0.0,0.000,116017.0,8247.754,0.0,0.0,0.0,-2109.4,-232.034
zubaciv01,615400.2,276981.6,-87543.8,-24283.4,1592739.2,40139.6,22360.720,0.0,-67337.6,732675.0,...,1244518.2,60396.0,441.886,1164069.0,41077.484,931712.2,1402987.0,6130.4,92810.2,8678.540

In [40]:
advanced_stats = pd.DataFrame(advanced_stats_avg, columns = advanced_stats.columns, index=advanced_stats_sum.index)

In [41]:
bball_ref

,Name,Probability,LastYear,hof,League_mvp,Count_mvp,Count_dpoy,All_stars,Count_finals_mvp,Championships,...,made_field_goals,made_free_throws,made_three_point_field_goals,minutes_played,offensive_rebounds,personal_fouls,points,steals,total_rebounds,turnovers
id,,,,,,,,,,,,,,,,,,,,,
abdulka01,Kareem Abdul-Jabbar,1.0000,1989,1,NBA,6,0,18,2,6.0,...,15837.0,6712.0,1.0,57446.0,2975.0,4657.0,38387.0,1160.0,17440.0,2527.0
jordami01,Michael Jordan,1.0000,2003,1,NBA,5,1,13,6,6.0,...,12192.0,7327.0,581.0,41011.0,1668.0,2783.0,32292.0,2514.0,6672.0,2924.0
russebi01,Bill Russell,1.0000,1969,1,NBA,5,0,12,0,11.0,...,5687.0,3148.0,0.0,40726.0,0.0,2592.0,14522.0,0.0,21620.0,0.0
bryanko01,Kobe Bryant,1.0000,2016,1,NBA,1,0,15,2,5.0,...,11719.0,8378.0,1827.0,48637.0,1499.0,3353.0,33643.0,1944.0,7047.0,4010.0
jamesle01,LeBron James,1.0000,2020,0,NBA,4,0,16,3,3.0,...,11838.0,7140.0,1727.0,46235.0,1443.0,2207.0,32543.0,1937.0,8880.0,4163.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wedmasc01,Scott Wedman,0.0150,1987,0,NaN,0,0,1,0,2.0,...,5153.0,1526.0,84.0,25927.0,1502.0,2549.0,11916.0,846.0,4355.0,883.0
leeda02,David Lee,0.0147,2017,0,NaN,0,0,2,0,1.0,...,4587.0,2057.0,1.0,24293.0,2150.0,2170.0,11232.0,625.0,7320.0,1454.0
finlemi01,Michael Finley,0.0145,2010,0,NaN,0,0,2,0,1.0,...,6696.0,2460.0,1454.0,37996.0,1121.0,1812.0,17306.0,996.0,4804.0,1629.0
brianfr01,Frankie Brian,0.0142,1956,0,NaN,0,0,2,0,0.0,...,1765.0,1849.0,0.0,7616.0,0.0,1127.0,5379.0,0.0,903.0,0.0
smithph01,Phil Smith,0.0140,1983,0,NaN,0,0,2,0,1.0,...,4007.0,1891.0,19.0,19166.0,588.0,1680.0,9924.0,734.0,1978.0,990.0

In [42]:
bball_ref = bball_ref.join(advanced_stats, on="id", how="left")

In [43]:
bball_ref["peak_win_shares"] = ws
bball_ref["peak_value_over_replacement_player"] = vorp

In [44]:
all_league = data["all_league_counts.csv"].copy()
all_league.set_index("id", inplace=True)
bball_ref = bball_ref.join(all_league.drop("Name", axis=1), on="id", how="left")

In [45]:
bball_ref.to_csv("merged.csv")

In [46]:
seasons = data["player_season_totals.csv"].copy()

In [47]:
seasons.team = seasons.team.apply(get_team)
seasons = seasons[["slug", "team"]]

In [48]:
import scipy

In [49]:
seasons = seasons.groupby("slug").agg(scipy.stats.mode)
seasons.team = seasons.team.apply(lambda x: x[0][0])

In [49]:
seasons.to_csv("most_common_teams.csv")

In [50]:
vorp

slug
abdelal01   -0.1
abdulka01    9.0
abdulma01    0.0
abdulma02    1.9
abdulta01    0.4
            ...
zipsepa01   -0.5
zizican01    0.2
zoetji01    -0.1
zopfbi01     0.0
zubaciv01    0.2
Name: value_over_replacement_player, Length: 4030, dtype: float64